name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to another repository
      uses: cpina/github-action-push-to-another-repository@v1.7.2
      with:
        source-directory: 'dist'
        destination-github-username: 'angrybird233'
        destination-repository-name: 'angrybird233.github.io'
        target-branch: 'main'
        github-token: ${{ secrets.GH_TOKEN }}
